language: python

python:
    - "3.5"


before_install:
  - sudo apt-get -y libgdal-dev
  - sudo apt-get install -y python-gdal

# install dependencies
install:
  - cd backend
  - pip install -r requirements-travis.txt

script:
  - pytest

notifications:
  email: false
